import React from 'react';

const initialState = {
    products: [
        {id: 1, name: 'Samsung Galaxy S20 Plus', image: 'p1.jpg', price: 20, discount: 2, discountPrice: 20 -2/100 * 20, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        {id: 2, name: 'Oneplus 8 Pro', image: 'p2.jpg', price: 23, discount: 4, discountPrice: 23 -4/100 * 23, quantity: 1, category: 'Fetured Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        {id: 3, name: 'Xiaomi Redmi Note 8 Pro', image: 'p3.jpg', price: 30, discount: 3, discountPrice: 30 -3/100 * 30, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        {id: 4, name: 'Apple Iphone 12', image: 'p4.jpg', price: 15, discount: 1, discountPrice: 15 -1/100 * 15, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        {id: 5, name: 'Samsung Galaxy Note 20 Ultra', image: 'p5.jpg', price: 20, discount: 5, discountPrice: 20 -5/100 * 20, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        {id: 6, name: 'OnePlus 8T 5G', image: 'p6.png', price: 25, discount: 2, discountPrice: 25 -2/100 * 25, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        {id: 7, name: 'Xiaomi Mi 10T Pro', image: 'p7.jpg', price: 18, discount: 2, discountPrice: 18 -2/100 * 18, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        {id: 8, name: 'Huawei P40 Pro', image: 'p8.jpg', price: 55, discount: 3, discountPrice: 55 -3/100 * 55, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        {id: 9, name: 'Samsung Galaxy S20 FE', image: 'p9.jpeg', price: 80, discount: 4, discountPrice: 80 -4/100 * 80, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        {id: 10, name: 'Samsung Galaxy A51', image: 'p10.webp', price: 110, discount: 50, discountPrice: 110 -50/100 * 110, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        {id: 11, name: 'Nokia 3310', image: 'p11.png', price: 210, discount: 20, discountPrice: 210 -20/100 * 210, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        {id: 12, name: 'OnePlus Nord N100', image: 'p12.png', price: 120, discount: 10, discountPrice: 120 -10/100 * 120, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
        // {id: 13, name: 'phoneR+', image: 'p1.jpg', price: 20, discount: 2, discountPrice: 20 -2/100 * 20, quantity: 1, category: 'Smart Phone', desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting. Remaining essentially unchanged." },
    ], 
    product: {},
}

export const ProductsReducer = (state = initialState, action) => {
    // console.log(typeof action.id);
    switch(action.type){
        case 'PRODUCT': return{
            ...state,
            product: state.products.find((product)=> product.id === parseInt(action.id)),
        }


        default: return state;
    }
}
